# Generated by Django 4.2.3 on 2023-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('Dept', models.CharField(max_length=10)),
                ('Salary', models.IntegerField(default=0, max_length=10)),
                ('Role', models.CharField(max_length=10)),
                ('phone', models.CharField(default=0, max_length=10)),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'office',
            },
        ),
    ]
