# Generated by Django 4.2.4 on 2023-09-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_employee_email_employee_password_employee_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password2',
        ),
    ]
